name: Tarea MongoDB

on: 
  push:

jobs:
  tarea:
    runs-on: ubuntu-latest
    container: mongo:6.0

    steps:
      - name: Impresión 1
        run: echo "Contenedor MongoDB levantado"

      - name: Impresión 2
        run: mongod --version

      - name: Impresión 3
        run: echo "¡MongoDB se está ejecutando correctamente!"
